version: '3'
services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  node-app:
    build: .
    container_name: node-app
    depends_on:
      - redis
    ports:
      - "3000:3000"
